apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-deployment
  template:
    metadata:
      labels:
        app: my-deployment
    spec:
      containers:
        - name: my-app-container
          image: akashmore947/my-app-image:master-5d55671ea93767a17b13dd9ce1e04aaf2806ff61
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
