apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-deployment
  template:
    metadata:
      labels:
        app: my-deployment
    spec:
      containers:
        - name: my-app-container
          image: akashmore947/my-app-image:master-b19cec2ba53a7a445f80598ead942c0739c1bd46
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
